Import ('env')



myenv = env

InstallDir = myenv['BINDIR_ServerTest']
SourcesDllErrorTable = [    'clErrorTable.cpp',
                            'clObjectCall.cpp',
                            '../clDatabaseColumn.cpp',
                            '../clIceClientLogging.cpp',
                            '../clIceClientServer.cpp',
                            '../ICE_LogApplication.cpp',
                            '../ICE_ServerApplication.cpp'
                        ]
ErrorTable = myenv.SharedLibrary('clErrorTable', SourcesDllErrorTable,
                                                LIBS=['libQt5Core',
                                                'libQt5Xml',
                                                'libQt5Network',
												'libpq',
												'libIce',
												'libIceDiscovery',
												'libIceLocatorDiscovery',
												'libIceSSL']
                                                )
myenv.Install (InstallDir + '/Objects', 'libclErrorTable.so')
#Operation
SourcesDllOperation = [    'clOperation.cpp',
                            'clObjectCall.cpp',
                            '../clDatabaseColumn.cpp',
                            '../clIceClientLogging.cpp',
                            '../clIceClientServer.cpp',
                            '../ICE_LogApplication.cpp',
                            '../ICE_ServerApplication.cpp'
                        ]
Operation = myenv.SharedLibrary('clOperation', SourcesDllOperation,
                                                LIBS=['libQt5Core',
                                                'libQt5Xml',
                                                'libQt5Network',
                                                'libpq',
												'libIce',
												'libIceDiscovery',
												'libIceLocatorDiscovery',
												'libIceSSL']
                                                )
myenv.Install (InstallDir + '/Objects', 'libclOperation.so')
